/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.143.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// InlineResponse20013 struct for InlineResponse20013
type InlineResponse20013 struct {
	Body System `json:"body,omitempty"`
}
