/*
RHSM-API

API for Red Hat Subscription Management

API version: 1.313.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// checks if the UpdateProviderAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProviderAccountRequest{}

// UpdateProviderAccountRequest struct for UpdateProviderAccountRequest
type UpdateProviderAccountRequest struct {
	Nickname string `json:"nickname"`
}

// NewUpdateProviderAccountRequest instantiates a new UpdateProviderAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProviderAccountRequest(nickname string) *UpdateProviderAccountRequest {
	this := UpdateProviderAccountRequest{}
	this.Nickname = nickname
	return &this
}

// NewUpdateProviderAccountRequestWithDefaults instantiates a new UpdateProviderAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProviderAccountRequestWithDefaults() *UpdateProviderAccountRequest {
	this := UpdateProviderAccountRequest{}
	return &this
}

// GetNickname returns the Nickname field value
func (o *UpdateProviderAccountRequest) GetNickname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nickname
}

// GetNicknameOk returns a tuple with the Nickname field value
// and a boolean to check if the value has been set.
func (o *UpdateProviderAccountRequest) GetNicknameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nickname, true
}

// SetNickname sets field value
func (o *UpdateProviderAccountRequest) SetNickname(v string) {
	o.Nickname = v
}

func (o UpdateProviderAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProviderAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nickname"] = o.Nickname
	return toSerialize, nil
}

type NullableUpdateProviderAccountRequest struct {
	value *UpdateProviderAccountRequest
	isSet bool
}

func (v NullableUpdateProviderAccountRequest) Get() *UpdateProviderAccountRequest {
	return v.value
}

func (v *NullableUpdateProviderAccountRequest) Set(val *UpdateProviderAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProviderAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProviderAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProviderAccountRequest(val *UpdateProviderAccountRequest) *NullableUpdateProviderAccountRequest {
	return &NullableUpdateProviderAccountRequest{value: val, isSet: true}
}

func (v NullableUpdateProviderAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProviderAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


