/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.113.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// SystemListMock struct for SystemListMock
type SystemListMock struct {
	Body       []System     `json:"body,omitempty"`
	Pagination ApiPageParam `json:"pagination,omitempty"`
}
