/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.143.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// PackageDetail PackageDetail wraps an errata package and adds a RefURL
type PackageDetail struct {
	Arch        string   `json:"arch,omitempty"`
	Checksum    string   `json:"checksum,omitempty"`
	ContentSets []string `json:"contentSets,omitempty"`
	DetailsUrl  string   `json:"details_url,omitempty"`
	Epoch       int32    `json:"epoch,omitempty"`
	Filename    string   `json:"filename,omitempty"`
	Name        string   `json:"name,omitempty"`
	Release     string   `json:"release,omitempty"`
	RepoTags    []string `json:"repoTags,omitempty"`
	Summary     string   `json:"summary,omitempty"`
	Version     string   `json:"version,omitempty"`
}
