/*
RHSM-API

API for Red Hat Subscription Management

API version: 1.366.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// checks if the UpdatedImagesList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatedImagesList{}

// UpdatedImagesList struct for UpdatedImagesList
type UpdatedImagesList struct {
	Body []UpdatedImage `json:"body,omitempty"`
}

// NewUpdatedImagesList instantiates a new UpdatedImagesList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatedImagesList() *UpdatedImagesList {
	this := UpdatedImagesList{}
	return &this
}

// NewUpdatedImagesListWithDefaults instantiates a new UpdatedImagesList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatedImagesListWithDefaults() *UpdatedImagesList {
	this := UpdatedImagesList{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *UpdatedImagesList) GetBody() []UpdatedImage {
	if o == nil || IsNil(o.Body) {
		var ret []UpdatedImage
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatedImagesList) GetBodyOk() ([]UpdatedImage, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *UpdatedImagesList) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given []UpdatedImage and assigns it to the Body field.
func (o *UpdatedImagesList) SetBody(v []UpdatedImage) {
	o.Body = v
}

func (o UpdatedImagesList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatedImagesList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	return toSerialize, nil
}

type NullableUpdatedImagesList struct {
	value *UpdatedImagesList
	isSet bool
}

func (v NullableUpdatedImagesList) Get() *UpdatedImagesList {
	return v.value
}

func (v *NullableUpdatedImagesList) Set(val *UpdatedImagesList) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatedImagesList) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatedImagesList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatedImagesList(val *UpdatedImagesList) *NullableUpdatedImagesList {
	return &NullableUpdatedImagesList{value: val, isSet: true}
}

func (v NullableUpdatedImagesList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatedImagesList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


