/*
RHSM-API

API for Red Hat Subscription Management

API version: 1.313.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// checks if the ShowErratum200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShowErratum200Response{}

// ShowErratum200Response struct for ShowErratum200Response
type ShowErratum200Response struct {
	Body *ErratumDetails `json:"body,omitempty"`
}

// NewShowErratum200Response instantiates a new ShowErratum200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShowErratum200Response() *ShowErratum200Response {
	this := ShowErratum200Response{}
	return &this
}

// NewShowErratum200ResponseWithDefaults instantiates a new ShowErratum200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShowErratum200ResponseWithDefaults() *ShowErratum200Response {
	this := ShowErratum200Response{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *ShowErratum200Response) GetBody() ErratumDetails {
	if o == nil || IsNil(o.Body) {
		var ret ErratumDetails
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShowErratum200Response) GetBodyOk() (*ErratumDetails, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *ShowErratum200Response) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given ErratumDetails and assigns it to the Body field.
func (o *ShowErratum200Response) SetBody(v ErratumDetails) {
	o.Body = &v
}

func (o ShowErratum200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShowErratum200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	return toSerialize, nil
}

type NullableShowErratum200Response struct {
	value *ShowErratum200Response
	isSet bool
}

func (v NullableShowErratum200Response) Get() *ShowErratum200Response {
	return v.value
}

func (v *NullableShowErratum200Response) Set(val *ShowErratum200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableShowErratum200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableShowErratum200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShowErratum200Response(val *ShowErratum200Response) *NullableShowErratum200Response {
	return &NullableShowErratum200Response{value: val, isSet: true}
}

func (v NullableShowErratum200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShowErratum200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


