/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.109.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"time"
)

// ErrataResponse struct for ErrataResponse
type ErrataResponse struct {
	AffectedProducts []string    `json:"affectedProducts,omitempty"`
	Bugzillas        []Reference `json:"bugzillas,omitempty"`
	CopyrightYear    string      `json:"copyrightYear,omitempty"`
	Cves             string      `json:"cves,omitempty"`
	Description      string      `json:"description,omitempty"`
	Id               string      `json:"id,omitempty"`
	// Date represents the date format used for API returns
	Issued time.Time `json:"issued,omitempty"`
	// Date represents the date format used for API returns
	LastUpdated  time.Time   `json:"lastUpdated,omitempty"`
	References   []Reference `json:"references,omitempty"`
	Severity     string      `json:"severity,omitempty"`
	Solution     string      `json:"solution,omitempty"`
	Summary      string      `json:"summary,omitempty"`
	Synopsis     string      `json:"synopsis,omitempty"`
	Type         string      `json:"type,omitempty"`
	TypeSeverity string      `json:"typeSeverity,omitempty"`
}
