/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.109.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// MyErrataListMock struct for MyErrataListMock
type MyErrataListMock struct {
	Body       []MyErratum  `json:"body,omitempty"`
	Pagination ApiPageParam `json:"pagination,omitempty"`
}
