/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.143.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// InlineResponse2005 struct for InlineResponse2005
type InlineResponse2005 struct {
	Body ErratumDetails `json:"body,omitempty"`
}
