/*
RHSM-API

API for Red Hat Subscription Management

API version: 1.300.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// ListSystemErrata200Response struct for ListSystemErrata200Response
type ListSystemErrata200Response struct {
	Body       []ErratumForSystem `json:"body,omitempty"`
	Pagination *APIPageParam      `json:"pagination,omitempty"`
}

// NewListSystemErrata200Response instantiates a new ListSystemErrata200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSystemErrata200Response() *ListSystemErrata200Response {
	this := ListSystemErrata200Response{}
	return &this
}

// NewListSystemErrata200ResponseWithDefaults instantiates a new ListSystemErrata200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSystemErrata200ResponseWithDefaults() *ListSystemErrata200Response {
	this := ListSystemErrata200Response{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *ListSystemErrata200Response) GetBody() []ErratumForSystem {
	if o == nil || o.Body == nil {
		var ret []ErratumForSystem
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSystemErrata200Response) GetBodyOk() ([]ErratumForSystem, bool) {
	if o == nil || o.Body == nil {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *ListSystemErrata200Response) HasBody() bool {
	if o != nil && o.Body != nil {
		return true
	}

	return false
}

// SetBody gets a reference to the given []ErratumForSystem and assigns it to the Body field.
func (o *ListSystemErrata200Response) SetBody(v []ErratumForSystem) {
	o.Body = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListSystemErrata200Response) GetPagination() APIPageParam {
	if o == nil || o.Pagination == nil {
		var ret APIPageParam
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSystemErrata200Response) GetPaginationOk() (*APIPageParam, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListSystemErrata200Response) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given APIPageParam and assigns it to the Pagination field.
func (o *ListSystemErrata200Response) SetPagination(v APIPageParam) {
	o.Pagination = &v
}

func (o ListSystemErrata200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullableListSystemErrata200Response struct {
	value *ListSystemErrata200Response
	isSet bool
}

func (v NullableListSystemErrata200Response) Get() *ListSystemErrata200Response {
	return v.value
}

func (v *NullableListSystemErrata200Response) Set(val *ListSystemErrata200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListSystemErrata200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListSystemErrata200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSystemErrata200Response(val *ListSystemErrata200Response) *NullableListSystemErrata200Response {
	return &NullableListSystemErrata200Response{value: val, isSet: true}
}

func (v NullableListSystemErrata200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSystemErrata200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
