/*
RHSM-API

API for Red Hat Subscription Management

API version: 1.313.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// checks if the PackageForSystemAdvisoriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PackageForSystemAdvisoriesInner{}

// PackageForSystemAdvisoriesInner struct for PackageForSystemAdvisoriesInner
type PackageForSystemAdvisoriesInner struct {
	Advisory *string `json:"advisory,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewPackageForSystemAdvisoriesInner instantiates a new PackageForSystemAdvisoriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackageForSystemAdvisoriesInner() *PackageForSystemAdvisoriesInner {
	this := PackageForSystemAdvisoriesInner{}
	return &this
}

// NewPackageForSystemAdvisoriesInnerWithDefaults instantiates a new PackageForSystemAdvisoriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageForSystemAdvisoriesInnerWithDefaults() *PackageForSystemAdvisoriesInner {
	this := PackageForSystemAdvisoriesInner{}
	return &this
}

// GetAdvisory returns the Advisory field value if set, zero value otherwise.
func (o *PackageForSystemAdvisoriesInner) GetAdvisory() string {
	if o == nil || IsNil(o.Advisory) {
		var ret string
		return ret
	}
	return *o.Advisory
}

// GetAdvisoryOk returns a tuple with the Advisory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageForSystemAdvisoriesInner) GetAdvisoryOk() (*string, bool) {
	if o == nil || IsNil(o.Advisory) {
		return nil, false
	}
	return o.Advisory, true
}

// HasAdvisory returns a boolean if a field has been set.
func (o *PackageForSystemAdvisoriesInner) HasAdvisory() bool {
	if o != nil && !IsNil(o.Advisory) {
		return true
	}

	return false
}

// SetAdvisory gets a reference to the given string and assigns it to the Advisory field.
func (o *PackageForSystemAdvisoriesInner) SetAdvisory(v string) {
	o.Advisory = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PackageForSystemAdvisoriesInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageForSystemAdvisoriesInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PackageForSystemAdvisoriesInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PackageForSystemAdvisoriesInner) SetUrl(v string) {
	o.Url = &v
}

func (o PackageForSystemAdvisoriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PackageForSystemAdvisoriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Advisory) {
		toSerialize["advisory"] = o.Advisory
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullablePackageForSystemAdvisoriesInner struct {
	value *PackageForSystemAdvisoriesInner
	isSet bool
}

func (v NullablePackageForSystemAdvisoriesInner) Get() *PackageForSystemAdvisoriesInner {
	return v.value
}

func (v *NullablePackageForSystemAdvisoriesInner) Set(val *PackageForSystemAdvisoriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePackageForSystemAdvisoriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePackageForSystemAdvisoriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackageForSystemAdvisoriesInner(val *PackageForSystemAdvisoriesInner) *NullablePackageForSystemAdvisoriesInner {
	return &NullablePackageForSystemAdvisoriesInner{value: val, isSet: true}
}

func (v NullablePackageForSystemAdvisoriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackageForSystemAdvisoriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


