/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.113.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// InlineResponse2003 struct for InlineResponse2003
type InlineResponse2003 struct {
	Body ExportJobResponse `json:"body,omitempty"`
}
