/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.109.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// ContentSetArchMock struct for ContentSetArchMock
type ContentSetArchMock struct {
	Body       []ErratumInContentSet `json:"body,omitempty"`
	Pagination ApiPageParam          `json:"pagination,omitempty"`
}
