/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.177.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// ErratumInContentSet ErratumInContentSet contains information on an erratum listed in a content set
type ErratumInContentSet struct {
	AdvisoryId *string `json:"advisoryId,omitempty"`
	Href       *string `json:"href,omitempty"`
	// Date represents the date format used for API returns
	PublishDate *string `json:"publishDate,omitempty"`
	Severity    *string `json:"severity,omitempty"`
	Synopsis    *string `json:"synopsis,omitempty"`
	Type        *string `json:"type,omitempty"`
}

// NewErratumInContentSet instantiates a new ErratumInContentSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErratumInContentSet() *ErratumInContentSet {
	this := ErratumInContentSet{}
	return &this
}

// NewErratumInContentSetWithDefaults instantiates a new ErratumInContentSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErratumInContentSetWithDefaults() *ErratumInContentSet {
	this := ErratumInContentSet{}
	return &this
}

// GetAdvisoryId returns the AdvisoryId field value if set, zero value otherwise.
func (o *ErratumInContentSet) GetAdvisoryId() string {
	if o == nil || o.AdvisoryId == nil {
		var ret string
		return ret
	}
	return *o.AdvisoryId
}

// GetAdvisoryIdOk returns a tuple with the AdvisoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErratumInContentSet) GetAdvisoryIdOk() (*string, bool) {
	if o == nil || o.AdvisoryId == nil {
		return nil, false
	}
	return o.AdvisoryId, true
}

// HasAdvisoryId returns a boolean if a field has been set.
func (o *ErratumInContentSet) HasAdvisoryId() bool {
	if o != nil && o.AdvisoryId != nil {
		return true
	}

	return false
}

// SetAdvisoryId gets a reference to the given string and assigns it to the AdvisoryId field.
func (o *ErratumInContentSet) SetAdvisoryId(v string) {
	o.AdvisoryId = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ErratumInContentSet) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErratumInContentSet) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ErratumInContentSet) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ErratumInContentSet) SetHref(v string) {
	o.Href = &v
}

// GetPublishDate returns the PublishDate field value if set, zero value otherwise.
func (o *ErratumInContentSet) GetPublishDate() string {
	if o == nil || o.PublishDate == nil {
		var ret string
		return ret
	}
	return *o.PublishDate
}

// GetPublishDateOk returns a tuple with the PublishDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErratumInContentSet) GetPublishDateOk() (*string, bool) {
	if o == nil || o.PublishDate == nil {
		return nil, false
	}
	return o.PublishDate, true
}

// HasPublishDate returns a boolean if a field has been set.
func (o *ErratumInContentSet) HasPublishDate() bool {
	if o != nil && o.PublishDate != nil {
		return true
	}

	return false
}

// SetPublishDate gets a reference to the given string and assigns it to the PublishDate field.
func (o *ErratumInContentSet) SetPublishDate(v string) {
	o.PublishDate = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *ErratumInContentSet) GetSeverity() string {
	if o == nil || o.Severity == nil {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErratumInContentSet) GetSeverityOk() (*string, bool) {
	if o == nil || o.Severity == nil {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *ErratumInContentSet) HasSeverity() bool {
	if o != nil && o.Severity != nil {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *ErratumInContentSet) SetSeverity(v string) {
	o.Severity = &v
}

// GetSynopsis returns the Synopsis field value if set, zero value otherwise.
func (o *ErratumInContentSet) GetSynopsis() string {
	if o == nil || o.Synopsis == nil {
		var ret string
		return ret
	}
	return *o.Synopsis
}

// GetSynopsisOk returns a tuple with the Synopsis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErratumInContentSet) GetSynopsisOk() (*string, bool) {
	if o == nil || o.Synopsis == nil {
		return nil, false
	}
	return o.Synopsis, true
}

// HasSynopsis returns a boolean if a field has been set.
func (o *ErratumInContentSet) HasSynopsis() bool {
	if o != nil && o.Synopsis != nil {
		return true
	}

	return false
}

// SetSynopsis gets a reference to the given string and assigns it to the Synopsis field.
func (o *ErratumInContentSet) SetSynopsis(v string) {
	o.Synopsis = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ErratumInContentSet) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErratumInContentSet) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ErratumInContentSet) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ErratumInContentSet) SetType(v string) {
	o.Type = &v
}

func (o ErratumInContentSet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AdvisoryId != nil {
		toSerialize["advisoryId"] = o.AdvisoryId
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.PublishDate != nil {
		toSerialize["publishDate"] = o.PublishDate
	}
	if o.Severity != nil {
		toSerialize["severity"] = o.Severity
	}
	if o.Synopsis != nil {
		toSerialize["synopsis"] = o.Synopsis
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableErratumInContentSet struct {
	value *ErratumInContentSet
	isSet bool
}

func (v NullableErratumInContentSet) Get() *ErratumInContentSet {
	return v.value
}

func (v *NullableErratumInContentSet) Set(val *ErratumInContentSet) {
	v.value = val
	v.isSet = true
}

func (v NullableErratumInContentSet) IsSet() bool {
	return v.isSet
}

func (v *NullableErratumInContentSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErratumInContentSet(val *ErratumInContentSet) *NullableErratumInContentSet {
	return &NullableErratumInContentSet{value: val, isSet: true}
}

func (v NullableErratumInContentSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErratumInContentSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
