/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.143.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// InlineResponse20015 struct for InlineResponse20015
type InlineResponse20015 struct {
	Body       []PackageForSystem `json:"body,omitempty"`
	Pagination ApiPageParam       `json:"pagination,omitempty"`
}
