/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.143.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// EnabledProduct Enabled Product represents a cloud access provider product
type EnabledProduct struct {
	EnabledQuantity int32    `json:"enabledQuantity,omitempty"`
	ImageGroups     []string `json:"imageGroups,omitempty"`
	Name            string   `json:"name,omitempty"`
	// ShortDate represents the short date format used for API returns where time precision is not needed
	NextRenewal   string `json:"nextRenewal,omitempty"`
	Sku           string `json:"sku,omitempty"`
	TotalQuantity int32  `json:"totalQuantity,omitempty"`
}
