/*
RHSM-API

API for Red Hat Subscription Management

API version: 1.366.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// checks if the ExportJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportJobResponse{}

// ExportJobResponse struct for ExportJobResponse
type ExportJobResponse struct {
	ExportID *string `json:"exportID,omitempty"`
	Href *string `json:"href,omitempty"`
}

// NewExportJobResponse instantiates a new ExportJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportJobResponse() *ExportJobResponse {
	this := ExportJobResponse{}
	return &this
}

// NewExportJobResponseWithDefaults instantiates a new ExportJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportJobResponseWithDefaults() *ExportJobResponse {
	this := ExportJobResponse{}
	return &this
}

// GetExportID returns the ExportID field value if set, zero value otherwise.
func (o *ExportJobResponse) GetExportID() string {
	if o == nil || IsNil(o.ExportID) {
		var ret string
		return ret
	}
	return *o.ExportID
}

// GetExportIDOk returns a tuple with the ExportID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportJobResponse) GetExportIDOk() (*string, bool) {
	if o == nil || IsNil(o.ExportID) {
		return nil, false
	}
	return o.ExportID, true
}

// HasExportID returns a boolean if a field has been set.
func (o *ExportJobResponse) HasExportID() bool {
	if o != nil && !IsNil(o.ExportID) {
		return true
	}

	return false
}

// SetExportID gets a reference to the given string and assigns it to the ExportID field.
func (o *ExportJobResponse) SetExportID(v string) {
	o.ExportID = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ExportJobResponse) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportJobResponse) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ExportJobResponse) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ExportJobResponse) SetHref(v string) {
	o.Href = &v
}

func (o ExportJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExportID) {
		toSerialize["exportID"] = o.ExportID
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	return toSerialize, nil
}

type NullableExportJobResponse struct {
	value *ExportJobResponse
	isSet bool
}

func (v NullableExportJobResponse) Get() *ExportJobResponse {
	return v.value
}

func (v *NullableExportJobResponse) Set(val *ExportJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExportJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExportJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportJobResponse(val *ExportJobResponse) *NullableExportJobResponse {
	return &NullableExportJobResponse{value: val, isSet: true}
}

func (v NullableExportJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


