/*
RHSM-API

API for Red Hat Subscription Management

API version: 1.366.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveProviderAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveProviderAccountRequest{}

// RemoveProviderAccountRequest struct for RemoveProviderAccountRequest
type RemoveProviderAccountRequest struct {
	Id string `json:"id"`
}

type _RemoveProviderAccountRequest RemoveProviderAccountRequest

// NewRemoveProviderAccountRequest instantiates a new RemoveProviderAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveProviderAccountRequest(id string) *RemoveProviderAccountRequest {
	this := RemoveProviderAccountRequest{}
	this.Id = id
	return &this
}

// NewRemoveProviderAccountRequestWithDefaults instantiates a new RemoveProviderAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveProviderAccountRequestWithDefaults() *RemoveProviderAccountRequest {
	this := RemoveProviderAccountRequest{}
	return &this
}

// GetId returns the Id field value
func (o *RemoveProviderAccountRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RemoveProviderAccountRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RemoveProviderAccountRequest) SetId(v string) {
	o.Id = v
}

func (o RemoveProviderAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveProviderAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *RemoveProviderAccountRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveProviderAccountRequest := _RemoveProviderAccountRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveProviderAccountRequest)

	if err != nil {
		return err
	}

	*o = RemoveProviderAccountRequest(varRemoveProviderAccountRequest)

	return err
}

type NullableRemoveProviderAccountRequest struct {
	value *RemoveProviderAccountRequest
	isSet bool
}

func (v NullableRemoveProviderAccountRequest) Get() *RemoveProviderAccountRequest {
	return v.value
}

func (v *NullableRemoveProviderAccountRequest) Set(val *RemoveProviderAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveProviderAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveProviderAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveProviderAccountRequest(val *RemoveProviderAccountRequest) *NullableRemoveProviderAccountRequest {
	return &NullableRemoveProviderAccountRequest{value: val, isSet: true}
}

func (v NullableRemoveProviderAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveProviderAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


