/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.177.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// PackageForSystemAdvisories struct for PackageForSystemAdvisories
type PackageForSystemAdvisories struct {
	Advisory *string `json:"advisory,omitempty"`
	Url      *string `json:"url,omitempty"`
}

// NewPackageForSystemAdvisories instantiates a new PackageForSystemAdvisories object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackageForSystemAdvisories() *PackageForSystemAdvisories {
	this := PackageForSystemAdvisories{}
	return &this
}

// NewPackageForSystemAdvisoriesWithDefaults instantiates a new PackageForSystemAdvisories object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageForSystemAdvisoriesWithDefaults() *PackageForSystemAdvisories {
	this := PackageForSystemAdvisories{}
	return &this
}

// GetAdvisory returns the Advisory field value if set, zero value otherwise.
func (o *PackageForSystemAdvisories) GetAdvisory() string {
	if o == nil || o.Advisory == nil {
		var ret string
		return ret
	}
	return *o.Advisory
}

// GetAdvisoryOk returns a tuple with the Advisory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageForSystemAdvisories) GetAdvisoryOk() (*string, bool) {
	if o == nil || o.Advisory == nil {
		return nil, false
	}
	return o.Advisory, true
}

// HasAdvisory returns a boolean if a field has been set.
func (o *PackageForSystemAdvisories) HasAdvisory() bool {
	if o != nil && o.Advisory != nil {
		return true
	}

	return false
}

// SetAdvisory gets a reference to the given string and assigns it to the Advisory field.
func (o *PackageForSystemAdvisories) SetAdvisory(v string) {
	o.Advisory = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PackageForSystemAdvisories) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageForSystemAdvisories) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PackageForSystemAdvisories) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PackageForSystemAdvisories) SetUrl(v string) {
	o.Url = &v
}

func (o PackageForSystemAdvisories) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Advisory != nil {
		toSerialize["advisory"] = o.Advisory
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullablePackageForSystemAdvisories struct {
	value *PackageForSystemAdvisories
	isSet bool
}

func (v NullablePackageForSystemAdvisories) Get() *PackageForSystemAdvisories {
	return v.value
}

func (v *NullablePackageForSystemAdvisories) Set(val *PackageForSystemAdvisories) {
	v.value = val
	v.isSet = true
}

func (v NullablePackageForSystemAdvisories) IsSet() bool {
	return v.isSet
}

func (v *NullablePackageForSystemAdvisories) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackageForSystemAdvisories(val *PackageForSystemAdvisories) *NullablePackageForSystemAdvisories {
	return &NullablePackageForSystemAdvisories{value: val, isSet: true}
}

func (v NullablePackageForSystemAdvisories) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackageForSystemAdvisories) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
