/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.113.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// ExportResponse struct for ExportResponse
type ExportResponse struct {
	ExportJobID string `json:"exportJobID,omitempty"`
	Href        string `json:"href,omitempty"`
}
