/*
RHSM-API

API for Red Hat Subscription Management

API version: 1.366.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// checks if the ListSubscriptions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSubscriptions200Response{}

// ListSubscriptions200Response struct for ListSubscriptions200Response
type ListSubscriptions200Response struct {
	// ListResponse is the actual collection of subscription details that gets rendered
	Body []DetailResponse `json:"body,omitempty"`
	Pagination *APIPageParam `json:"pagination,omitempty"`
}

// NewListSubscriptions200Response instantiates a new ListSubscriptions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSubscriptions200Response() *ListSubscriptions200Response {
	this := ListSubscriptions200Response{}
	return &this
}

// NewListSubscriptions200ResponseWithDefaults instantiates a new ListSubscriptions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSubscriptions200ResponseWithDefaults() *ListSubscriptions200Response {
	this := ListSubscriptions200Response{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *ListSubscriptions200Response) GetBody() []DetailResponse {
	if o == nil || IsNil(o.Body) {
		var ret []DetailResponse
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSubscriptions200Response) GetBodyOk() ([]DetailResponse, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *ListSubscriptions200Response) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given []DetailResponse and assigns it to the Body field.
func (o *ListSubscriptions200Response) SetBody(v []DetailResponse) {
	o.Body = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListSubscriptions200Response) GetPagination() APIPageParam {
	if o == nil || IsNil(o.Pagination) {
		var ret APIPageParam
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSubscriptions200Response) GetPaginationOk() (*APIPageParam, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListSubscriptions200Response) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given APIPageParam and assigns it to the Pagination field.
func (o *ListSubscriptions200Response) SetPagination(v APIPageParam) {
	o.Pagination = &v
}

func (o ListSubscriptions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSubscriptions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableListSubscriptions200Response struct {
	value *ListSubscriptions200Response
	isSet bool
}

func (v NullableListSubscriptions200Response) Get() *ListSubscriptions200Response {
	return v.value
}

func (v *NullableListSubscriptions200Response) Set(val *ListSubscriptions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListSubscriptions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListSubscriptions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSubscriptions200Response(val *ListSubscriptions200Response) *NullableListSubscriptions200Response {
	return &NullableListSubscriptions200Response{value: val, isSet: true}
}

func (v NullableListSubscriptions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSubscriptions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


