/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.143.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// EnabledCloudAccessProvider Enabled Cloud Access Provider details including products and accounts.
type EnabledCloudAccessProvider struct {
	Accounts  []EnabledProviderAccount `json:"accounts,omitempty"`
	Name      string                   `json:"name,omitempty"`
	Products  []EnabledProduct         `json:"products,omitempty"`
	ShortName string                   `json:"shortName,omitempty"`
}
