/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.113.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// DetailResponse struct for DetailResponse
type DetailResponse struct {
	ContractNumber string `json:"contractNumber,omitempty"`
	// Date represents the date format used for API returns
	EndDate  string `json:"endDate,omitempty"`
	Pools    []Pool `json:"pools,omitempty"`
	Quantity string `json:"quantity,omitempty"`
	Sku      string `json:"sku,omitempty"`
	// Date represents the date format used for API returns
	StartDate          string `json:"startDate,omitempty"`
	Status             string `json:"status,omitempty"`
	SubscriptionName   string `json:"subscriptionName,omitempty"`
	SubscriptionNumber string `json:"subscriptionNumber,omitempty"`
}
