/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.109.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm
// InlineResponse20011 struct for InlineResponse20011
type InlineResponse20011 struct {
	Body System `json:"body,omitempty"`
}
