/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.113.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// InlineResponse307 struct for InlineResponse307
type InlineResponse307 struct {
	Body DownloadLink `json:"body,omitempty"`
}
