/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.177.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

import (
	"encoding/json"
)

// InlineObject struct for InlineObject
type InlineObject struct {
	Id          string  `json:"id"`
	NewNickname *string `json:"newNickname,omitempty"`
}

// NewInlineObject instantiates a new InlineObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject(id string) *InlineObject {
	this := InlineObject{}
	this.Id = id
	return &this
}

// NewInlineObjectWithDefaults instantiates a new InlineObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObjectWithDefaults() *InlineObject {
	this := InlineObject{}
	return &this
}

// GetId returns the Id field value
func (o *InlineObject) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InlineObject) SetId(v string) {
	o.Id = v
}

// GetNewNickname returns the NewNickname field value if set, zero value otherwise.
func (o *InlineObject) GetNewNickname() string {
	if o == nil || o.NewNickname == nil {
		var ret string
		return ret
	}
	return *o.NewNickname
}

// GetNewNicknameOk returns a tuple with the NewNickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject) GetNewNicknameOk() (*string, bool) {
	if o == nil || o.NewNickname == nil {
		return nil, false
	}
	return o.NewNickname, true
}

// HasNewNickname returns a boolean if a field has been set.
func (o *InlineObject) HasNewNickname() bool {
	if o != nil && o.NewNickname != nil {
		return true
	}

	return false
}

// SetNewNickname gets a reference to the given string and assigns it to the NewNickname field.
func (o *InlineObject) SetNewNickname(v string) {
	o.NewNickname = &v
}

func (o InlineObject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.NewNickname != nil {
		toSerialize["newNickname"] = o.NewNickname
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject struct {
	value *InlineObject
	isSet bool
}

func (v NullableInlineObject) Get() *InlineObject {
	return v.value
}

func (v *NullableInlineObject) Set(val *InlineObject) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject(val *InlineObject) *NullableInlineObject {
	return &NullableInlineObject{value: val, isSet: true}
}

func (v NullableInlineObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
