/*
 * RHSM-API
 *
 * API for Red Hat Subscription Management
 *
 * API version: 1.113.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gorhsm

// InlineResponse2008 struct for InlineResponse2008
type InlineResponse2008 struct {
	Body       []ContentSet `json:"body,omitempty"`
	Pagination ApiPageParam `json:"pagination,omitempty"`
}
